### ISSUE TITLE
Identify the reception of a new RDS message in the presence of RDS bursts

### ISSUE THREAD

**Issue by jpdias92** [achilikin/RdSpi#2]
I'm using this program within a system where I use single RDS messages (type 00A) as a control channel. It would be useful if there was a way of knowing where a new RDS message arrived. Therefore, I would like to know if it is safe to manually set the registers that I'm reading to something like -1, after retrieving its current value, and when a new RDS arrived, that register would change to a different value, letting me now that what I'm reading is from a different RDS message. Otherwise, the register would be set for too long. I need to receive a new RDS message each 80 ms or something like that.

**Comment by achilikin** [comment]
RDSR bit of regs[STATUSRSSI] can be used as an indication that new RDS group has arrived. It is set for about 40 ms after new RDS messasge has been written to registers RDSA to RDSD. Have a look at section 4.4 https://www.sparkfun.com/datasheets/BreakoutBoards/Si4702-03-C19-1.pdf

**Comment by jpdias92** [comment]
Thanks achilikin!
