### ISSUE TITLE
bug in scan mode

### ISSUE THREAD

**Issue by koalabang** [achilikin/RdSpi#3]
hello, i have a bug in scan mode or spectrum mode. Pi code is fixing to 0000 .
example :
 9260 ---------------------------------- 34 ST
 9330 ---------------------------------------- 40 ST 0000 'R CAMPUS'
 9400 --------------- 15
 9440 -------------------------------- 32 ST
 9460 ----------------------------- 29
 9500 ------------------------------------------ 42 ST 0000 ' RIRE   '
 9600 --------------------------- 27
 9620 ---------------------------- 28
 9660 --------------------------------------------------- 51 ST 0000 '   FUN  '
 9750 ----------------------------------------------- 47 ST 0000 '  MOUV  '
 9780 ----------------------------- 29
 9880 ------------------------------- 31
10290 -------------------------------- 32 ST
10430 ----------------------------------------- 41 ST 0000 '  RTL   '
10470 ---------------------------------------------- 46
10510 --------------------------------------------- 45
10640 ---------------------------------------------- 46 ST 0000 '  RFM   '

**Comment by achilikin** [comment]
Fixed in the latest version
