### ISSUE TITLE
Raspberry 3

### ISSUE THREAD

**Issue by jerlenbu** [achilikin/RdSpi#4]
Hello achilikin,
I'm using the raspi 3 in combinition with the si470x chip.
I have already established the connection with the chip, as shown here:
**root@raspberrypi:/home/pi/wiringPi/RdSpi# i2cdetect -y 1
0 1 2 3 4 5 6 7 8 9 a b c d e f
00: — — — — — — — — — — — — —
10: 10 — — — — — — — — — — — — — — —
20: — — — — — — — — — — — — — — — —
30: — — — — — — — — — — — — — — — —
40: — — — — — — — — — — — — — — — —
50: — — — — — — — — — — — — — — — —
60: — — — — — — — — — — — — — — — —
70: — — — — — — — —**

After that I want to reset the chip with the following command: **root@raspberrypi:/home/pi/wiringPi/RdSpi# ./rdspi reset
Unable to read Si4703!
Communication error**
And now I get Communication error. So have you an idea why is it so? Are your scripts combatable  to Rasperry 3?
Thank you.

**Comment by BridgJoe** [comment]
Hello jerlenbu,

same problem here.
Seems to be a problem with the handling of the reset pin.
I have uncomment line 97 "rpi_pin_export(SI_RESET, RPI_INPUT);" of main.c
and recompile the code again.
Before this line of code, the command "i2cdetect -y 1" can detect the board,
After this line the board disappears and the error message appears.
Now everything works fine.
Please give a feedback if this works for you.

Thanks!

Best regards.

**Comment by jerlenbu** [comment]
Guten Tag und vielen Dank für Ihre Nachricht.
 
Herr Johannes Erlenbusch ist nicht mehr bei uns beschäftigt.
Bitte wenden Sie sich zukünftig an:
 
Herr Michael Seefeldt
Fon   +49 (0) 71 91. 34 43 - 0
Fax   +49 (0) 71 91. 34 43 - 55
E-Mail: info@seefeldt-direktmarketing.de
 
Vielen Dank für Ihr Verständnis.


Mit freundlichen Grüßen
Michael Seefeldt

*********************************************************************
michael seefeldt. DirektMarketing GmbH
Beim Erlenwäldchen 20. 71522 Backnang
Fon   +49 (0) 71 91. 34 43 - 0
Fax   +49 (0) 71 91. 34 43 - 44
*********************************************************************
Geschäftsführer: Michael Seefeldt
Sitz der Gesellschaft: Backnang
Amtsgericht Stuttgart     HRB: 729199
Ust.-ID-Nr.: DE 263707931     Steuer-Nr.: 51049/19020  
_________________________________________________________
Bei dieser Nachricht handelt es sich um vertrauliche Informationen,
welche nur für den oder die benannten Empfänger persönlich bestimmt
sind. Sollten Sie nicht der oder die genannten Empfänger sein, sind Sie
verpflichtet, die Information unverzüglich zu vernichten.

**Comment by achilikin** [comment]
Hello jerlenbu

I do not have Rpi3 to test with, but I had this problem on one of Si4703 boards abd RPi2. It disappeared after I'd connected to RST pin to a pull up resistor.

Regards,
Andrey

**Comment by jerlenbu** [comment]
Hello,
thanks for the replies. 
to Andrey: The pull up resistor don't helped.
to BridgeJoe: your answer helped me - Thank you very much!!!

I have to add some details to my hardware. I have now the Raspberry 2 Model B and I had the same problems as with the Raspberry 3. I have the Si470x FM-Receiver.

Thanks to all
